Feature/h2db
PaleRoom/DemoShop pull request #2
Opened 2022-11-25 14:16 UTC by PaleRoom

Added H2  Base

2022-11-25 16:52 UTC, GUR-ok requested changes

2022-11-25 16:52 UTC, GUR-ok commented on pom.xml
> +			<scope>test</scope>
- [ ] У тебя есть зависмость с дефолтным скоупом. Скоуп тест не нужен

2022-11-25 16:52 UTC, GUR-ok commented on pom.xml
> +			<groupId>org.springframework.boot</groupId>
- [ ] К этой задаче не относится. Как и остальное ниже

2022-11-25 16:52 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/DemoShopApplication.java
> +import org.springframework.scheduling.annotation.EnableScheduling;
Лишнее

2022-11-25 16:52 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/ProductControllerImpl.java
>  import org.springframework.web.bind.annotation.*;
Не должно быть схлопнутых импортов

2022-11-25 16:52 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/ProductControllerImpl.java
>      private final ProductServiceImpl productServiceImpl;
Тут должно быть заинжекчено через интерфейс.. ProductService. Мб упустил в тот раз. Проверь везде плз. Если есть интерфейс и импл, то инжектим через интерфейс

2022-11-25 16:52 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
> +
Наоборот тут не нужна пустая строка)

2022-11-25 16:52 UTC, GUR-ok commented on src/main/resources/application.yml
> +
Лишнии изменения в пулреквесте. Потом посмотришь какими коммитами менялся файл и почему, и будет вводить в заблуждение

2022-11-29 16:09 UTC, PaleRoom commented on pom.xml
> +			<scope>test</scope>
Убрал

2022-11-29 16:10 UTC, PaleRoom commented on src/main/resources/application.yml
> +
Да, буду смотреть.

2022-11-30 04:48 UTC, GUR-ok approved these changes

2022-12-07 06:37 UTC, merged