Feature/scheduling
PaleRoom/DemoShop pull request #3
Opened 2022-11-25 14:18 UTC by PaleRoom

Added Price-Increase sheduler

2022-11-25 17:49 UTC, GUR-ok requested changes

2022-11-25 17:49 UTC, GUR-ok commented on pom.xml
> +			<scope>test</scope>
- [x] тут библиотеки, которые не имеют отношения к этому пр. Давай добавим плз только то, что нужно

2022-11-25 17:49 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/config/SchedulerConfig.java
> +@ConditionalOnProperty(name = "app.scheduling.enabled", matchIfMissing = true)
Супер! Правда по дефолту в требованиях было false) уточни плз

2022-11-25 17:49 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/repository/ProductRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_READ)
Отлично! Для собственного опыта вне пр попробуй поставить оптимистик лок, если еще не пробовал. В пр оставить так, как сейчас.

2022-11-25 17:49 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/PriceIncreaseScheduler.java
> +    private ProductServiceImpl productServiceImpl;
- [ ] Инжект через интерфейс

2022-11-25 17:49 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/PriceIncreaseScheduler.java
> +@Component
- [ ] Давай весь бин сделаем через conditional on property. Так же как и конфиг для шедулинга. Или бин создай там в конфиге и тут без component.

2022-11-25 17:49 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/PriceIncreaseScheduler.java
> +    private double mod;
- [ ] Что будет если параметр не задан? Цены обнулятся?

2022-11-25 17:49 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
> +        Thread.sleep(30000);
Оставь тут комент в коде, что этот слип в учебных целях для изучения транзакций

2022-11-25 17:49 UTC, GUR-ok commented on src/main/resources/application.yml
> +    period: 15000
Тут комент, что это 15сек

2022-11-25 17:49 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/PriceIncreaseScheduler.java
> +        this.productServiceImpl = productServiceImpl;
- [ ] Два раза подставляется мод. И в поле, и тут. Можно через ломбоковские аннотации. Req.args.constr. или all.args.constr избавиться от рукописного конструктора.. поля final

2022-11-25 17:49 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
>          if (productRepository.findById(product.getId()).get().getAmount() != product.getAmount()) {
- [ ] Давай плз в этом пр перепишем метод апдейт. План такой: 

1. По айди дергаем продукт. Если там пусто то эксепшн. Через опшнл это обработать. setId(id) - плохая практика.
2. В jpa repo сделай метод, который принимает имя, возвращает опшнл айди. Нативным sql запросом.
3. Если пусто или айди совпадает с тем, что в реквесте, то ок. Иначе эксепшн, что имя должно быть уникально. Метод сервиса findOneByName уходит в небытие)
4. Сетим ему все поля из реквеста сеттарами. Если в реквесте поле нулл - не меняем поле на продукте. Тернарными выражениями можно воспользоваться например.
5. Не нужно использовать конвертер который преобразует реквест в продукт. Мы продукт получаем из бд, а не создаем новый. Удалить лишний класс конвертера. 
6. Убрать проверку на изменение количества. Сделать триггером в бд автоматическое изменение поля даты)
7. Посмотреть и порадоваться как все просто и красиво стало)

2022-11-25 17:49 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
> +        System.out.println("INCREASING IS SLEEPING NOW");
- [ ] Давай уберем все sout в программе. И залогируем все как надо через @Slf4j logger

2022-11-25 17:49 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductService.java
> +@Transactional
Давай над интерфейсом без transactional: А если будет реализация сервиса без реляционной бд?

2022-11-25 17:49 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
> +@Transactional
Readonly можно добавить над первыми двумя find методами

2022-11-29 16:11 UTC, PaleRoom commented on pom.xml
> +			<scope>test</scope>
Убрал лишнее

2022-11-29 16:13 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/config/SchedulerConfig.java
> +@ConditionalOnProperty(name = "app.scheduling.enabled", matchIfMissing = true)
Я опять залил с true:/

2022-11-29 16:13 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/repository/ProductRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_READ)
Принято!

2022-11-29 16:14 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/service/PriceIncreaseScheduler.java
> +@Component
Конфиг убрал, один класс шедьюлера оставил.

2022-11-29 16:14 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/service/PriceIncreaseScheduler.java
> +    private double mod;
Добавил дефолтное значение в @Value

2022-11-29 16:15 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/service/PriceIncreaseScheduler.java
> +        this.productServiceImpl = productServiceImpl;
Сделал через Req.args

2022-11-29 16:20 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
>          if (productRepository.findById(product.getId()).get().getAmount() != product.getAmount()) {
Сделал. 
1.Лишний конвертер убрал. 
2.Через тернарный получается вызов вызова вызова - малочитаемо, не стал применять. 
3.Функция и триггер добавлены через скрипт liquibase.
Стало красиво, но зависимо от типа БД. Экспириенс - неоценим.

2022-11-29 16:23 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
> +        System.out.println("INCREASING IS SLEEPING NOW");
Сделал аналоги sout в двух классах, конфиг в .yml. Пишется в консоль и файл. Для разнообразия кое-что выводится через debug - попробовал вывести переменную.

2022-11-30 07:16 UTC, GUR-ok requested changes

2022-11-30 07:16 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
> +    public Product findOneEnt(UUID id) {
- [x] Зачем этот метод сделан публичным? Лучше его вообще не делать. Получить и обработать optional прям в методе update

2022-11-30 07:16 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/scheduling/PriceIncreaseScheduler.java
> +@Slf4j
добавь пустую строку

2022-11-30 07:16 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/scheduling/PriceIncreaseScheduler.java
> +    private final ProductService productService;
пустую строку

2022-11-30 07:16 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/scheduling/PriceIncreaseScheduler.java
> +
тут не нужна

2022-11-30 07:16 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
> +        log.info("Product updated");
в логирование добавь айди измененного продукта

2022-11-30 07:16 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
> +        Product product = findOneEnt(id);
- [x] если метод findIdByName не нашел айди по имени, не должен бросаться ProductNotFoundException. Метод вспомогательный. Если там пустой optional, это означает, что имя для нас уникально (его нет в базе) и можно идти дальше. Обработка через выброс и catch исключения все усложняет, тем более он ignored. Метод findIdByName не делать публичным и лучше вообще убрать, если он не используется вне сервиса. А тут будет примерно так (если убрать два метода findIdByName и findOneEnt:
...
        Product product = productRepository.findById(id).orElseThrow(ProductNotFoundException::new);
        if (request.getName() != null && checkUnique(request.getName(), id)) {
            product.setName(request.getName());
        }
...      

    private boolean checkUnique(final String name, final UUID id) {
        final boolean check = productRepository.findIdByName(name).map(entId -> Objects.equals(entId, id)).orElse(true);
        if (!check) {
            throw new ProductUniqueException("name must be unique bla bla");
        }
        return true;
    }

Т.е. тут 2 момента:
1. без надобности методы не делать публичными
2. без надобности не бросать исключения. Если в методе findIdByName убрать выброс исключения, то получается одна строчка, ради которой нет смысла делать отдельный метод. С методом findOneEnt похожая история. там тоже одна строчка.

2022-11-30 07:23 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/config/SchedulerConfig.java
> +@ConditionalOnProperty(name = "app.scheduling.enabled", matchIfMissing = true)
Видел, пофиг ладно

2022-12-08 13:48 UTC, GUR-ok approved these changes

2022-12-08 13:48 UTC, merged