Feature/jpaspec
PaleRoom/DemoShop pull request #7
Opened 2022-12-17 09:25 UTC by PaleRoom

2022-12-17 15:59 UTC, GUR-ok requested changes

2022-12-17 15:59 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/ProductController.java
> +    GetListResponse searchProducts(SearchProductRequest searchProductRequest) throws IOException;
Пусть метод возвращает просто List ProductResponse. Класс GetListResponse не нужен и связанный с ним конвертер. Метод getProducts() пусть тоже возвращает List ProductResponse. Конвертеры ConvertToGetListResponse и ConvertToResponseList не нужны + у них стремные имена) Посмотришь на них - и ниче не понятно) И там и там лист..)

2022-12-17 15:59 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/ProductControllerImpl.java
> +        List<ProductDTO> ListDTO = productService.findAll();
- [ ] Давай все это стримом. List GetProductResponse list =productService.findAll().stream().map(dto -> conversionService.convert(dto, GetProductResponse.class).collect(Collectors::toList);
Метод будет возвращать List GetProductResponse

2022-12-17 15:59 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/ProductControllerImpl.java
> +        List<GetProductResponse> listGPR = new ArrayList<>();
Тоже самое. Сделай через стрим. Все обработки коллекций через стрим.

2022-12-17 15:59 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/SearchedToPDFsaver.java
> +public class SearchedToPDFsaver {
Оба сейвера документов вынести в один класс в пакете сервис. В пакете контроллера их точно не должно быть. Ну и вызываться они не должны из контроллера. В сервисе же есть отдельный метод для поиска по спецификации. вот там и давай их вызовем

2022-12-17 15:59 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/SearchedToPDFsaver.java
> +    public void saveSearchedToPdf(GetListResponse listResponse) throws IOException {
Методы должны работать с List ProductDto, а не с сущностями контроллера

2022-12-17 15:59 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/SearchedToXlsSaver.java
> +    public void SaveSearchedToXls(GetListResponse listResponse) throws IOException {
аналогично, принимать должны List ProductDto

2022-12-17 15:59 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/request/SearchProductRequest.java
> +    String name;
поля private

2022-12-17 15:59 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/repository/specification/ProductSpecification.java
> +            return null;
Возвращать нулл - это работает? Может нужно возвращать Specification.where(null)?

2022-12-17 15:59 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
> +        List<ProductDTO> listDTO = new ArrayList<>();
Обработать стримом

2022-12-17 15:59 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/immutable/ImmutableSearchProductRequest.java
> +    String name;
Тут все ок - private не нужно, т.к. value. Value дает private final. Поэтому и получается иммутабельный класс

2022-12-17 15:59 UTC, GUR-ok commented on src/main/resources/db/changelog/add-availability-column.xml
> +
Добавить preCondition, что такая таблица существует

2022-12-17 15:59 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/converter/ConvertToResponseList.java
>              list.add(conversionService.convert(product, GetProductResponse.class));
Давай вообще этот конвертер уберем. У тебя есть конвертер для одиночного объекта ConvertToGetProductResponse (кстати лучше его назвать по-другому - ProductDtoToGetProductResponseConverter, а то у тебя непонятно по названию что во что конвертится). А преобразования списка в список делать стримом находу, вызывая конвертер единичного объекта. Конвертить список в список - плохая практика.

2022-12-17 15:59 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/ProductControllerImpl.java
> +        searchedToPDFsaver.saveSearchedToPdf(responseList);
Это уйдет в сервис searchProducts метод

2022-12-19 08:27 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/repository/specification/ProductSpecification.java
> +            return null;
Сделал через criteriaBuilder.conjunction();

2022-12-19 08:37 UTC, PaleRoom commented on src/main/resources/db/changelog/add-availability-column.xml
> +
Добавил во всех скриптах. При создании таблицы - проверяет ее отсутствие.

2022-12-19 16:19 UTC, GUR-ok requested changes

2022-12-19 16:19 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/ProductControllerImpl.java
> +        List <GetProductResponse>list =
Нужно сразу return без объявления list. А .map и .collect с новой строки

2022-12-19 16:19 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/ProductControllerImpl.java
> +        List <GetProductResponse>list = productService.searchProducts(immutableSearchProductRequest).stream().map(dto ->
77-80 строки не нужны

2022-12-19 16:19 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/repository/specification/ProductSpecification.java
> +        return (root, query, criteriaBuilder) -> {
return (root, query, criteriaBuilder) -> {
            if (availability == null) {
                return criteriaBuilder.conjunction();
            } else {
                return criteriaBuilder.equal(root.get(Product_.AVAILABILITY), availability) ;
            }
        };

2022-12-19 16:19 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
> +        searchResultSaver.saveSearchedToPdf(searchedList);
вызов двух сейверов давай в трай-кетч обернем и если исключение отловилось, то просто ошибку залогируем. Не хотим запарывать весь запрос, если не смогли сохранить отчет. Вывести инфу по товарам же мы сможем. Из сигнатуры метода убрать throws

2022-12-19 16:19 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
> +        return searchedList;
перед return всегда пустая строка, если метод не состоит из одного return

2022-12-19 16:19 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/ProductControllerImpl.java
> +        return productService.searchProducts(immutableSearchProductRequest).stream().map(dto ->
.map .collect с новой строки

2022-12-19 16:19 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/converter/ProductDtoToGetProductResponseConverter.java
> +final class ProductDtoToGetProductResponseConverter implements Converter<ProductDTO, GetProductResponse> {
final убрать, сделать public. Остальные конвертеры переименуй плз тоже

2022-12-19 16:19 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductService.java
>      @Transactional
Я б на методах интерфейса тут transactional не ставил.. т.к. реализация impl может быть разная - в т.ч. и без бд вообще

2022-12-19 16:19 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/ProductServiceImpl.java
> +        List<ProductDTO> searchedList = productRepository.findAll(specs).stream().map(product ->
.map .collect с новой строки

2022-12-19 16:25 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/controller/ProductControllerImpl.java
> +        List <GetProductResponse>list = productService.searchProducts(immutableSearchProductRequest).stream().map(dto ->
Косяк - это я набивал и не убрал.

2022-12-19 16:27 UTC, GUR-ok requested changes

2022-12-19 16:27 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/ProductControllerImpl.java
> +    private final SearchResultSaver searchResultSaver;
лишнее поле

2022-12-19 17:02 UTC, GUR-ok requested changes

2022-12-19 17:02 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/SearchResultSaver.java
> +        if (valueOfCell instanceof Integer) {
А почему нельзя просто cell.setCellValue(valueOfCell.toString())?

2022-12-19 17:02 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/SearchResultSaver.java
> +        FileOutputStream fileOut = new FileOutputStream("Searched_" + LocalDateTime.now().format(formatter) + ".xls");
try (FileOutputStream fileOut = new FileOutputStream("Searched_" + LocalDateTime.now().format(formatter) + ".xls")) {
            workbook.write(fileOut);
            workbook.close(); 
        }

2022-12-19 17:02 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/SearchResultSaver.java
> +    private XSSFWorkbook workbook;
Идея предлагает сделать из этого локальную переменную (на 76 строке). И sheet тоже не нужно выносить в поле.

2022-12-19 17:16 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/service/SearchResultSaver.java
> +        if (valueOfCell instanceof Integer) {
Назначение типов для ячеек Excel

2022-12-19 17:39 UTC, GUR-ok approved these changes

2022-12-19 18:16 UTC, merged