Feature/exchangeoutput
PaleRoom/DemoShop pull request #8
Opened 2022-12-17 10:19 UTC by PaleRoom

2022-12-17 16:21 UTC, GUR-ok requested changes

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/DemoShopApplication.java
> +@EnableCaching
А в cacheConfig недостаточно данной аннотации?

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/DemoShopApplication.java
> +
Нужно следить за пустыми строками) она тут лишняя. лучше все просмотреть, чтобы не было лишних пустых строк перед фигурными скобками

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/ProductControllerImpl.java
> +        List<ProductDTO> ListDTO = productService.findAll();
Не оч хорошо, что ты эту ветку сделал из ветки c jpa..( тогда правь сначала тот пр, и еще раз посмотрим этот

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/exchanging/ExchangeTakingClient.java
> +    Double takeRateFromURL ();
просто takeRate.. почему FromURL? ты же урл не передаешь сюда

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/exchanging/ExchangeRate.java
> +    private Double exchangeRate;
пусть поле называется usdExchangeRate.. потом добавим eur

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/exchanging/ExchangeTakingClientImpl.java
> +        if (resp != null) {
Давай без if. Одним Optional.ofNullable(resp).map(r -> Optional.ofNullable(resp.getExchangeRate()).orElseThrow...

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/exchanging/ExchangeTakingClientStub.java
> +        double max = 120.0;
Вынести тут в константные поля

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/exchanging/ExchangeTakingProvider.java
> +        } catch (HttpServerErrorException.ServiceUnavailable
Давай просто catch (Exception e). Сразу все любые эксепшены отловим

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/exchanging/ExchangeTakingProvider.java
> +            ObjectMapper objectMapper = new ObjectMapper();
Логику вынести в этом классе в приватный метод

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/exchanging/ExchangeTakingProvider.java
> +            rate = exchangeTakingClient.takeRateFromURL();
Логику вынести в приватный метод в этом классе

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/exchanging/ExchangeTakingProvider.java
> +        return rate;
Когда вынесешь в приватные методы, можно написать все одной строкой: Double rate = Optional.ofNullable(getRemoteRate).orElse(getLocalRate).orElseThrow... Без объявления и инициализации вначале Double rate = null.. сразу return и эта структура с опшнл. Логирование делать в приватных методах

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/response/GetProductAdvice.java
> +public class GetProductAdvice implements ResponseBodyAdvice<GetProductResponse> {
хм. может сделаем пакет advice? в пакете контроллер

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/response/GetProductAdvice.java
> +        return className.contains("ProductControllerImpl") && methodName.contains("getOneProduct");
А как же методы возвращающие список? ) у них цена не переводится в $?

2022-12-17 16:21 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/repository/specification/ProductSpecification.java
> +    public static Specification<Product> lessPrice(Double price) {
Да, нужно было эту задачу делать независимо, отпочковываться от девелоп, а не от jpaSpec ветки.. Задания вроде не связаны. Но не трогаем сейчас. Просто сначала смержим jpaSpec. Просто сейчас выходит мы не сможем смержить сначала эту ветку. А если то задание вообще отменят?

2022-12-17 16:37 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/response/GetProductAdvice.java
> +    private ExchangeTakingProvider exchangeTakingProvider;
а почему тут не private final и не RequiredArgsConstructor?

2022-12-21 12:29 UTC, GUR-ok requested changes

2022-12-21 12:29 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/advice/ListGetProductAdvice.java
> +                                .price(product.getPrice() / rate)
- [ ] не нужно билдером новый объект делать. .map(p -> p.setPrice(p.getPrice() / rate))...

2022-12-21 12:29 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/exchanging/ExchangeTakingClientImpl.java
> +        System.out.println(resp);
давай sout избегать. Через лог

2022-12-21 12:29 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/exchanging/ExchangeTakingClientImpl.java
> +                .map(r -> Optional.ofNullable(resp.getUsdExchangeRate()).orElseThrow(() ->
.orElseThrow с новой строки. И он тут дублируется=)

2022-12-21 12:29 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/exchanging/ExchangeTakingClientStub.java
> +
- [ ] Добавь тут         
log.info("STUB method " + Thread.currentThread().getStackTrace()[0].getMethodName() + " of class" +
                this.getClass().getSimpleName() + " called");

2022-12-21 16:56 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/controller/exchanging/ExchangeTakingClientImpl.java
> +        System.out.println(resp);
Да, не почистил. Добавил в лог.

2022-12-21 18:46 UTC, GUR-ok approved these changes

2022-12-21 18:46 UTC, merged