Feature/orders
PaleRoom/DemoShop pull request #9
Opened 2023-01-04 13:20 UTC by PaleRoom

2023-01-06 09:56 UTC, GUR-ok requested changes

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/exception/customerException/CustomerErrorResponse.java
> +public class CustomerErrorResponse {
Давай сделаем один общий класс ErrorDetails, который заменит ProductErrorResponse, CustomerErrorResponse, OrderErrorResponse

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/exception/orderException/OrdertErrorResponse.java
> +public class OrdertErrorResponse {
Нигде не используется.

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler
нет исключений, связанных с Order

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/exception/orderException/OrderNotCreatedException.java
> +public class OrderNotCreatedException extends RuntimeException{
Класс не используется

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/exception/orderException/OrdertNotUpdatedException.java
> +public class OrdertNotUpdatedException extends  RuntimeException{
Класс не используется. Удалить

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/CustomerServiceImpl.java
> +        try {
Давай так все-таки не будем делать. Ты вызываешь метод в этом сервисе findOneByEmail, который идет в репозиторий, потом конвертит или бросает исключение CustomerNotFoundException. Ты это исключение ловишь и т.д. Можно просто вызывать сразу репозиторий, а не метод сервиса findOneByEmail.
        customerRepository.findByEmail(customer.getEmail())
                .ifPresent(c -> {
                            throw new CustomerNotCreatedException("This Customer is already exists!");
                        }
                );

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/CustomerServiceImpl.java
> +        } catch (CustomerNotFoundException ignored) {
Аналогично изменить и в других сервисах

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/repository/CustomerRepository.java
> +    List<Customer> findAll();
Зачем тут лочить записи при запросе? Кстати в ProductRepository назови такой метод findAllLocked. Чтобы не переопределять родной findAll. Чтоб можно было вызывать как метод с блокировкой, так и обычный.

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/repository/CustomerRepository.java
> +public interface CustomerRepository extends JpaRepository<Customer, UUID>, JpaSpecificationExecutor<Customer> {
JpaSpecificationExecutor наверно не нужен

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/repository/OrderRepository.java
> +public interface OrderRepository extends JpaRepository<Order, UUID>, JpaSpecificationExecutor<Order> {
JpaSpecificationExecutor наверно не нужен

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/model/OrderedProduct.java
> +   private Order ownerOrder;
ownerOrder сбивает с толку. Просто order

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/model/OrderedProduct.java
> +   private Product ownerProduct;
Просто product

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/model/Order.java
> +    @OneToMany(mappedBy = "ownerOrder", cascade = CascadeType.REMOVE)
mappedBy = "order" после того как переименуешь ownerOrder

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/model/Product.java
> +    private List<OrderedProduct> orderedProducts;
Здесь это не обязательно.  ManyToOne может быть однонаправленным. Достаточно двунаправленной связи order<->OrderedProduct

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/CustomerController.java
> +    UUID createOrder(@PathVariable("id") UUID id);
должно быть в orderController

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/CustomerController.java
> +     List<GetOrderResponse> getCustomersOrders (@PathVariable("id") UUID id);
и это наверно тоже

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/CustomerController.java
> +@RequestMapping("/default")
/customers

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/OrderController.java
> +@RequestMapping("/default")
/orders

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/ProductController.java
>  @RequestMapping("/default")
/products

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/model/Order.java
> +    @Nullable
Как это заказ без заказчика? )

2023-01-06 09:56 UTC, GUR-ok commented on src/main/resources/db/changelog/create-changeset-customer-table.XML
> +            <column name="customer_update" type="datetime">
<column name="customer_update" type="DATETIME(3)" remarks="Дата обновления пользователя"
                    defaultValueDate="NOW()">

2023-01-06 09:56 UTC, GUR-ok commented on src/main/resources/db/changelog/create-changeset-customer-table.XML
> +            <column name="id" type="uuid">
Добавить везде remarks=

2023-01-06 09:56 UTC, GUR-ok commented on src/main/resources/db/changelog/create-changeset-on-update-customer-trigger.XML
> +<?xml version="1.0" encoding="UTF-8"?>
Триггеры это хардкор. Давай в entity просто поставим аннотацию  @UpdateTimestamp над     private LocalDateTime updatedAt; Новые триггеры убрать. Триггер про изменения количества на товаре оставить, там было другое задание. (Чтоб дата изменялась ТОЛЬКО когда изменяется количество). А тут нам пофиг, дату новую ставим когда любое поле customer поменялось. Хвтатит и аннотации.

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/immutable/productImutable/ImmutableUpdateProductRequest.java
> +package ru.ncs.DemoShop.service.immutable.productImutable;
Раскидай по пакетам иначе: пакет service, в нем 3 пакета: order, product, customer. в каждом data и immutable. aop вынести вне пакета сервис.  SearchResultSaver вынести в пакет utils. пометить класс как @UtilityClass. его методы станут статическими. Убрать инжект SearchResultSaver и вызывать его методы как статические через название класса. Пакет converter пока оставить в пакете сервис

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/OrderController.java
> +@Tag(name = "Orderr service", description = "the Order API with description tag annotation")
Order**r**

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/OrderController.java
> +
лишние пустые строки

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/OrderController.java
> +//    @PostMapping
не должно быть комментированного кода

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/request/customerRequest/CreateCustomerRequest.java
> +    @Email
С этой аннотацией есть проблемка: mymail.@mail.ru она считает невалидным. но такой email возможен. Попробуй передать в запросе

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/request/customerRequest/CreateCustomerRequest.java
> +    @NotEmpty(message = "customer patronymic  should be not Empty")
Сustomer patronymic should not be blank. А лучше везде писать по-русски)

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/request/customerRequest/CreateCustomerRequest.java
> +
NotEmpty заменить на NotBlank. Иначе можно вводить строки с одними пробелами

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/request/customerRequest/UpdateCustomerRequest.java
> +    @NotEmpty(message = "customer name should be not Empty")
с notEmpty аналогично

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/response/GetCustomerResponse.java
> +    UUID id;
private

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/response/GetFullOrderResponse.java
> +    UUID id;
private

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/response/GetOrderResponse.java
> +    UUID id;
private

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/response/ProductInOrder.java
> +    String productName;
private

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/response/ProductInOrder.java
> +public class ProductInOrder {
ProductDetails

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/exception/GlobalExceptionHandler.java
> +//        return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST); // 401
Убрать закомментированный код

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST); // 401
В нескольких местах: // 400 а не 401

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/exception/customerException/CustomerErrorResponse.java
> +@Getter
геттер не нужен. есть в value

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/exception/customerException/CustomerNotUniqueException.java
> +public class CustomerNotUniqueException extends RuntimeException{
Не оч нравится такое название. Скорее ты его используешь как EmailAlreadyExistsException

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/exception/customerException/CustomerNotUpdatedException.java
> +public class CustomerNotUpdatedException extends RuntimeException{
Не нужно совсем)

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/exception/orderException/OrdertErrorResponse.java
> +@Getter
геттер не нужен

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/model/OrderedProduct.java
> +@IdClass(OrderedId.class)
Есть еще вариант через @EmbeddedId.. почитай про него плз. Тут оставляем так.

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/CustomerService.java
> +    CustomerDTO findOne(UUID id);
Пришла пора писать джавадоки. На каждый метод в интерфейсе написать javadoc: что метод делает, какие параметры принимает, что возвращает. И если бросает исключения, их тоже указать.
Пример:
/**
   * Этот метод используется для сложения двух целых чисел. Это
   * простейшая форма метода класса, просто чтобы
   * показать использование различных тегов javadoc.
   * @param numA Это первый параметр метода addNum 
   * @param numB Это второй параметр метода addNum 
   * @return int Это возвращает сумму numA и numB.
   */
   public int addNum(int numA, int numB) {
      return numA + numB;
   }

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/OrderService.java
> +    OrderDTO findOne(UUID id);
джавадоки =)

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/controller/converter/orderConverter/OrderDtoToGetFullOrderResponseConverter.java
> +
обработать стримом, а не через forEach и  prList.add(pr)

2023-01-06 09:56 UTC, GUR-ok commented on src/main/java/ru/ncs/DemoShop/service/OrderServiceImpl.java
> +        List<OrderDTO> listDTO = new ArrayList<>();
обработать стримом

2023-01-10 08:07 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/repository/CustomerRepository.java
> +    List<Customer> findAll();
Поторопился. Зато теперь узнал, что для findAlllocked нужно писать @Query (иначе он пытается искать атрибут Locked в сущности), Lock не вешается на нативный запрос, так как Lock срабатывает до непосредственно SQL-запроса, поэтому в @Query JPQL-запросы.

2023-01-10 12:20 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/controller/request/customerRequest/CreateCustomerRequest.java
> +    @Email
регулярным выражением забил)

2023-01-10 12:37 UTC, PaleRoom commented on src/main/java/ru/ncs/DemoShop/model/Product.java
> +    private List<OrderedProduct> orderedProducts;
Спасибо. У меня действительно это не используется.

2023-01-11 18:15 UTC, GUR-ok approved these changes

2023-01-11 18:21 UTC, merged